### ISSUE TITLE
Problems with some Forgemods dependencies (MalisisDoors)

### ISSUE THREAD

**Issue by Yldales** [dscalzi/HeliosLauncher#103]
Hi,

I'm encountering an issue when trying to add [MalisisCore 6.5.1](https://media.forgecdn.net/files/2680/892/malisiscore-1.12.2-6.5.1.jar) and [MalisisDoor 7.3.0](https://media.forgecdn.net/files/2526/674/malisisdoors-1.12.2-7.3.0.jar) to a modpack running with Forge 1.12.2-14.23.5.2854. The Forge loading screen is interrupted by this message:

> You must include the right dependencies for **MalisisDoors**:
> Require **malisiscore** any (missing)

**forgeModList.json**
```json
{
    "repositoryRoot": "absolute:C:\\Users\\Me\\AppData\\Roaming\\.helioslauncher\\common\\modstore",
    "modRef": [
        "net.malisis.core:malisiscore:1.12.2-6.5.1-SNAPSHOT",
        "net.malisis.doors:malisisdoors:1.12.2-7.3.0"
    ]
}
```
**latest.log**
```log
[20:55:34] [Client thread/FATAL]: net.minecraftforge.fml.common.MissingModsException: Mod malisisdoors (MalisisDoors) requires [malisiscore]
[20:55:34] [Client thread/ERROR]: An exception was thrown, the game will display an error screen and halt.
net.minecraftforge.fml.common.MissingModsException: Mod malisisdoors (MalisisDoors) requires [malisiscore]
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:266) ~[Loader.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:572) ~[Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```

I've tried to :

- Use [this version of MalisisCore](https://ore.spongepowered.org/Dockter/MalisisCore).
- In the distribution file, set malisiscore-1.12.2-6.5.1.jar as a Library.
- In the distribution file, set malisiscore-1.12.2-6.5.1.jar as a File.

**Comment by TheFlash787** [comment]
Hey!

This is currently an issue with the upstream Nebula where it doesn't contain a check for a blank version, or a version with '-SNAPSHOT' included (which forgeModList doesn't quite know how to use). 

You can use this commit inside of your own Nebula build to fix this: https://github.com/ModRealms-Network/Nebula/commit/03607adc4f019c4e5e77f06518d0e85ae7a24064

Since you may run into other issues later down the line (not necessarily with MalisisCore, but with optional mod ordering), I'd also recommend using this commit which will sort all mods by their name (previously it excluded optional mods, which broke load orders). https://github.com/ModRealms-Network/Nebula/commit/c203cb2f71d9ecebd2d6dbee0dc0b69ee085cebd

I hope this helps!

**Comment by dscalzi** [comment]
I added the two changes noted above to base Nebula. Do you know why exactly the `-SNAPSHOT` causing the loader to choke btw?

**Comment by TheFlash787** [comment]
> 
> 
> I added the two changes noted above to base Nebula. Do you know why exactly the `-SNAPSHOT` causing the loader to choke btw?

Thank you. But sadly I don't, I think it's only due to how it's being loaded with the forgeModList and that it must somehow be handled differently on Forge's end (compared to just using the mod folder).

**Comment by dscalzi** [comment]
@Yldales can you link your distribution url so I can try to figure out the problem? You can DM me on discord if you don't want to post it here.

**Comment by dscalzi** [comment]
MalisisCore works fine for me, use this version https://www.curseforge.com/minecraft/mc-mods/malisiscore

The one on sponge is probably a server-side sponge mod only.
