### ISSUE TITLE
Impossible de build pour linux

### ISSUE THREAD

**Issue by Banane480** [dscalzi/HeliosLauncher#221]
Quand je veux mettre en .appimage pour linux ca fait ca : 

**PS C:\Users\aidan\Desktop\ERANGEL\launcher\erangellauncher> npm run dist:linux

> erangellauncher@3.0.1 dist:linux
> npm run dist -- -l

> erangellauncher@3.0.1 dist
> electron-builder build "-l"

  • electron-builder  version=22.14.13 os=10.0.19044
  • loaded configuration  file=C:\Users\aidan\Desktop\ERANGEL\launcher\erangellauncher\electron-builder.yml
  • writing effective config  file=dist\builder-effective-config.yaml
  • packaging       platform=linux arch=x64 electron=17.1.0 appOutDir=dist\linux-unpacked
  • scheduling remote build  target=appImage arch=x64
  • cannot get, wait  error=Get "https://service.electron.build/find-build-agent?no-cache=1h6prio": dial tcp 51.15.76.176:443: connectex: Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée.
                      attempt=0
                      waitTime=2
  • cannot get, wait  error=Get "https://service.electron.build/find-build-agent?no-cache=1h6prio": dial tcp 51.15.76.176:443: connectex: Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée.
                      attempt=1
                      waitTime=4
  • cannot get, wait  error=Get "https://service.electron.build/find-build-agent?no-cache=1h6prio": dial tcp 51.15.76.176:443: connectex: Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée.
                      attempt=2
                      waitTime=6
  ⨯ Get "https://service.electron.build/find-build-agent?no-cache=1h6prio": dial tcp 51.15.76.176:443: connectex: Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée.  
  ⨯ C:\Users\aidan\Desktop\ERANGEL\launcher\erangellauncher\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  failedTask=build stackTrace=Error: C:\Users\aidan\Desktop\ERANGEL\launcher\erangellauncher\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE 
    at ChildProcess.<anonymous> (C:\Users\aidan\Desktop\ERANGEL\launcher\erangellauncher\node_modules\builder-util\src\util.ts:250:14)
    at Object.onceWrapper (node:events:640:26)
    at ChildProcess.emit (node:events:520:28)
    at ChildProcess.cp.emit (C:\Users\aidan\Desktop\ERANGEL\launcher\erangellauncher\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
From previous event:
    at processImmediate (node:internal/timers:466:21)
From previous event:
    at RemoteBuilder.build (C:\Users\aidan\Desktop\ERANGEL\launcher\erangellauncher\node_modules\app-builder-lib\src\remoteBuilder\RemoteBuilder.ts:51:28)
de_modules\app-builder-lib\src\linuxPackager.ts:105:30)
    at async Promise.all (index 1)
    at AsyncTaskManager.awaitTasks (C:\Users\aidan\Desktop\ERANGEL\launcher\erangellauncher\node_modules\builder-util\src\asyncTaskManager.ts:65:25)
    at Packager.doBuild (C:\Users\aidan\Desktop\ERANGEL\launcher\erangellauncher\node_modules\app-builder-lib\src\packager.ts:453:5)
    at Object.executeFinally (C:\Users\aidan\Desktop\ERANGEL\launcher\erangellauncher\node_modules\builder-util\src\promise.ts:12:14)
    at Packager._build (C:\Users\aidan\Desktop\ERANGEL\launcher\erangellauncher\node_modules\app-builder-lib\src\packager.ts:376:31)
    at Packager.build (C:\Users\aidan\Desktop\ERANGEL\launcher\erangellauncher\node_modules\app-builder-lib\src\packager.ts:337:12)
    at Object.executeFinally (C:\Users\aidan\Desktop\ERANGEL\launcher\erangellauncher\node_modules\builder-util\src\promise.ts:12:14)
PS C:\Users\aidan\Desktop\ERANGEL\launcher\erangellauncher> npm run dist:linux

> erangellauncher@3.0.1 dist:linux
> npm run dist -- -l

> erangellauncher@3.0.1 dist
> electron-builder build "-l"

  • electron-builder  version=22.14.13 os=10.0.19044
  • loaded configuration  file=C:\Users\aidan\Desktop\ERANGEL\launcher\erangellauncher\electron-builder.yml
  • writing effective config  file=dist\builder-effective-config.yaml
  • packaging       platform=linux arch=x64 electron=17.1.0 appOutDir=dist\linux-unpacked
  • scheduling remote build  target=appImage arch=x64
  • cannot get, wait  error=Get "https://service.electron.build/find-build-agent?no-cache=1h6prkg": dial tcp 51.15.76.176:443: connectex: Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée.
                      attempt=0
                      waitTime=2
  • cannot get, wait  error=Get "https://service.electron.build/find-build-agent?no-cache=1h6prkg": dial tcp 51.15.76.176:443: connectex: Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée.
                      attempt=1
                      waitTime=4
  • cannot get, wait  error=Get "https://service.electron.build/find-build-agent?no-cache=1h6prkg": dial tcp 51.15.76.176:443: connectex: Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée.
                      attempt=2
                      waitTime=6
  ⨯ Get "https://service.electron.build/find-build-agent?no-cache=1h6prkg": dial tcp 51.15.76.176:443: connectex: Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée.  
  ⨯ C:\Users\aidan\Desktop\ERANGEL\launcher\erangellauncher\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  failedTask=build stackTrace=Error: C:\Users\aidan\Desktop\ERANGEL\launcher\erangellauncher\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE 
    at ChildProcess.<anonymous> (C:\Users\aidan\Desktop\ERANGEL\launcher\erangellauncher\node_modules\builder-util\src\util.ts:250:14)
    at Object.onceWrapper (node:events:640:26)
    at ChildProcess.emit (node:events:520:28)
    at ChildProcess.cp.emit (C:\Users\aidan\Desktop\ERANGEL\launcher\erangellauncher\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
From previous event:
    at processImmediate (node:internal/timers:466:21)
From previous event:
    at RemoteBuilder.build (C:\Users\aidan\Desktop\ERANGEL\launcher\erangellauncher\node_modules\app-builder-lib\src\remoteBuilder\RemoteBuilder.ts:51:28)
    at RemoteTarget.finishBuild (C:\Users\aidan\Desktop\ERANGEL\launcher\erangellauncher\node_modules\app-builder-lib\src\linuxPackager.ts:105:30)
    at async Promise.all (index 1)
    at AsyncTaskManager.awaitTasks (C:\Users\aidan\Desktop\ERANGEL\launcher\erangellauncher\node_modules\builder-util\src\asyncTaskManager.ts:65:25)
    at Packager.doBuild (C:\Users\aidan\Desktop\ERANGEL\launcher\erangellauncher\node_modules\app-builder-lib\src\packager.ts:453:5)
    at Object.executeFinally (C:\Users\aidan\Desktop\ERANGEL\launcher\erangellauncher\node_modules\builder-util\src\promise.ts:12:14)
    at Packager._build (C:\Users\aidan\Desktop\ERANGEL\launcher\erangellauncher\node_modules\app-builder-lib\src\packager.ts:376:31)
    at Packager.build (C:\Users\aidan\Desktop\ERANGEL\launcher\erangellauncher\node_modules\app-builder-lib\src\packager.ts:337:12)
    at Object.executeFinally (C:\Users\aidan\Desktop\ERANGEL\launcher\erangellauncher\node_modules\builder-util\src\promise.ts:12:14)
PS C:\Users\aidan\Desktop\ERANGEL\launcher\erangellauncher>**

**Comment by gamernitro999** [comment]
1. the creator isn't french so ask in english it will help a lot (le créateur n'es pas français donc demande en français ça aidera beaucoup)
2. i think you can't cross-compile so to compile for linux go on a linux installation (je pense qu'on ne peut pas cross-compiler donc pour compiler pour linux fait le depuis un installation linux)

**Comment by Banane480** [comment]
Ok je vais essayer sur linux

**Comment by drori200** [comment]
> 1. the creator isn't french so ask in english it will help a lot (le créateur n'es pas français donc demande en français ça aidera beaucoup)
> 2. i think you can't cross-compile so to compile for linux go on a linux installation (je pense qu'on ne peut pas cross-compiler donc pour compiler pour linux fait le depuis un installation linux)

The creator is a Frenchman, but to get the most help you would have to write in english

**Comment by gamernitro999** [comment]
> > 1. the creator isn't french so ask in english it will help a lot (le créateur n'es pas français donc demande en français ça aidera beaucoup)
> > 2. i think you can't cross-compile so to compile for linux go on a linux installation (je pense qu'on ne peut pas cross-compiler donc pour compiler pour linux fait le depuis un installation linux)
> 
> The creator is a Frenchman, but to get the most help you would have to write in english

yes by writing in english you'll have more help but no dscalzi isn't french

**Comment by dscalzi** [comment]
Build for linux on linux. Also this:

```
• cannot get, wait error=Get "https://service.electron.build/find-build-agent?no-cache=1h6prio": dial tcp 51.15.76.176:443: connectex: Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée.
```

**Comment by GeekCornerGH** [comment]
> > 1. the creator isn't french so ask in english it will help a lot (le créateur n'es pas français donc demande en français ça aidera beaucoup)
> > 2. i think you can't cross-compile so to compile for linux go on a linux installation (je pense qu'on ne peut pas cross-compiler donc pour compiler pour linux fait le depuis un installation linux)
> 
> The creator is a Frenchman, but to get the most help you would have to write in english

@dscalzi isn't french, he comes from USA lol
