### ISSUE TITLE
App threw an error during load

### ISSUE THREAD

**Issue by justinsanjp** [dscalzi/HeliosLauncher#310]
App threw an error during load
[SyntaxError: Expected "#", "\n", "\r" or [ \t] but "Y" found.] {
  expected: [
    { type: 'literal', value: '#', description: '"#"' },
    { type: 'literal', value: '\n', description: '"\\n"' },
    { type: 'literal', value: '\r', description: '"\\r"' },
    { type: 'class', value: '[ \\t]', description: '[ \\t]' }
  ],
  found: 'Y',
  offset: 728,
  line: 20,
  column: 19
}

**Comment by justinsanjp** [comment]
VSCode says:
Uncaught Error Error: No such binding was linked: electron_common_v8_util
    at _linkedBinding (node:internal/bootstrap/realm:172:34)
    at getElectronBinding (file:///C:/Users/justin/Desktop/HeliosLauncher-master/node_modules/@electron/remote/dist/src/common/get-electron-binding.js:6:24)
    at <anonymous> (file:///C:/Users/justin/Desktop/HeliosLauncher-master/node_modules/@electron/remote/dist/src/main/server.js:13:39)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at <anonymous> (file:///C:/Users/justin/Desktop/HeliosLauncher-master/node_modules/@electron/remote/dist/src/main/index.js:4:16)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at <anonymous> (file:///C:/Users/justin/Desktop/HeliosLauncher-master/node_modules/@electron/remote/main/index.js:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at <anonymous> (file:///C:/Users/justin/Desktop/HeliosLauncher-master/index.js:1:20)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at executeUserEntryPoint (node:internal/modules/run_main:135:12)
    at <anonymous> (node:internal/main/run_main_module:28:49)
