### ISSUE TITLE
There's a bug that won't play if you make it a 1.21.3 version.

### ISSUE THREAD

**Issue by interacp** [dscalzi/HeliosLauncher#366]
In version 1.21.1, when you click play, Minecraft launches shortly after the download completes with a completion message. However, in version 1.21.3, there’s a bug where the launcher freezes on the completion message after all downloads are finished, and Minecraft does not launch.

**Comment by GeekCornerGH** [comment]
Hi, could you provide some logs please?

**Comment by GeekCornerGH** [comment]
You'll want to copy them from `ctrl+shift+i`

**Comment by interacp** [comment]
here conole log

```[2024-11-12 13시 19분 3초] [info] [Preloader]: Loading..
C:\Users\acpro\Documents\GitHub\dosaonline\node_modules\winston\lib\winston\transports\console.js:90 [2024-11-12 13시 19분 3초] [info] [ConfigManager]: Successfully Loaded
C:\Users\acpro\Documents\GitHub\dosaonline\node_modules\winston\lib\winston\transports\console.js:90 [2024-11-12 13시 19분 3초] [info] [Preloader]: Cleaned natives directory.
C:\Users\acpro\Documents\GitHub\dosaonline\node_modules\winston\lib\winston\transports\console.js:90 [2024-11-12 13시 19분 3초] [info] [Preloader]: Loaded distribution index.
C:\Users\acpro\Documents\GitHub\dosaonline\node_modules\winston\lib\winston\transports\console.js:90 [2024-11-12 13시 19분 3초] [info] [Landing]: Refreshing Mojang Statuses..
C:\Users\acpro\Documents\GitHub\dosaonline\node_modules\winston\lib\winston\transports\console.js:90 [2024-11-12 13시 19분 3초] [info] [UICore]: UICore Initializing..
C:\Users\acpro\Documents\GitHub\dosaonline\node_modules\winston\lib\winston\transports\console.js:90 [2024-11-12 13시 19분 3초] [info] [Landing]: Refreshing Server Status
node:internal/url:806 Uncaught (in promise) TypeError: Invalid URL
    at new URL (node:internal/url:806:29)
    at landing.js:970:26
    at new Promise (<anonymous>)
    at loadNews (landing.js:967:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async initNews (landing.js:822:18)
landing.js:248 Object
uicore.js:30 The console is dark and full of terrors.
uicore.js:31 If you've been told to paste something here, you're being scammed.
uicore.js:32 Unless you know exactly what you're doing, close this window.
C:\Users\acpro\Documents\GitHub\dosaonline\node_modules\winston\lib\winston\transports\console.js:90 [2024-11-12 13시 19분 14초] [info] [Landing]: Launching game..
C:\Users\acpro\Documents\GitHub\dosaonline\node_modules\winston\lib\winston\transports\console.js:90 [2024-11-12 13시 19분 14초] [info] [Landing]: Jvm Details {
  semver: { major: 21, minor: 0, patch: 3 },
  semverStr: '21.0.3',
  vendor: 'Eclipse Adoptium',
  path: 'C:\\Program Files\\Eclipse Adoptium\\jdk-21.0.3.9-hotspot'
}
C:\Users\acpro\Documents\GitHub\dosaonline\node_modules\winston\lib\winston\transports\console.js:90 [2024-11-12 13시 19분 14초] [info] [Landing]: Refreshing Server Status
C:\Users\acpro\Documents\GitHub\dosaonline\node_modules\winston\lib\winston\transports\console.js:90 [2024-11-12 13시 19분 14초] [info] [LaunchSuite]: Validating files.
node:internal/url:806 Uncaught (in promise) TypeError: Invalid URL
    at new URL (node:internal/url:806:29)
    at landing.js:970:26
    at new Promise (<anonymous>)
    at loadNews (landing.js:967:21)
    at async initNews (landing.js:822:18)
URL @ node:internal/url:806
(anonymous) @ landing.js:970
loadNews @ landing.js:967
await in loadNews
onDistroRefresh @ uibinder.js:138
dlAsync @ landing.js:461
await in dlAsync
(anonymous) @ landing.js:118
processTicksAndRejections @ node:internal/process/task_queues:95
landing.js:248 {version: {…}, players: {…}, description: {…}, retrievedAt: 1731385154308}
C:\Users\acpro\Documents\GitHub\dosaonline\node_modules\helios-core\dist\dl\AssetGaurdTransmitter.js:30 [_] [2024-11-12 13시 19분 14초] [info] [ReceiverExecutor]: Receiver process started.
C:\Users\acpro\Documents\GitHub\dosaonline\node_modules\winston\lib\winston\transports\console.js:90 [2024-11-12 13시 19분 16초] [debug] [Transmitter]: Received validate progress 20
C:\Users\acpro\Documents\GitHub\dosaonline\node_modules\winston\lib\winston\transports\console.js:90 [2024-11-12 13시 19분 17초] [debug] [Transmitter]: Received validate progress 40
C:\Users\acpro\Documents\GitHub\dosaonline\node_modules\winston\lib\winston\transports\console.js:90 [2024-11-12 13시 19분 17초] [debug] [Transmitter]: Received validate progress 60
C:\Users\acpro\Documents\GitHub\dosaonline\node_modules\winston\lib\winston\transports\console.js:90 [2024-11-12 13시 19분 17초] [debug] [Transmitter]: Received validate progress 80
C:\Users\acpro\Documents\GitHub\dosaonline\node_modules\winston\lib\winston\transports\console.js:90 [2024-11-12 13시 19분 17초] [debug] [Transmitter]: Received validate progress 100
C:\Users\acpro\Documents\GitHub\dosaonline\node_modules\winston\lib\winston\transports\console.js:90 [2024-11-12 13시 19분 17초] [info] [Transmitter]: Received validation complete.
C:\Users\acpro\Documents\GitHub\dosaonline\node_modules\winston\lib\winston\transports\console.js:90 [2024-11-12 13시 19분 17초] [info] [LaunchSuite]: No invalid files, skipping download.
C:\Users\acpro\Documents\GitHub\dosaonline\node_modules\helios-core\dist\dl\AssetGaurdTransmitter.js:30 [_] [2024-11-12 13시 19분 17초] [info] [ReceiverExecutor]: Disconnect singal received, shutting down.
C:\Users\acpro\Documents\GitHub\dosaonline\node_modules\winston\lib\winston\transports\console.js:90 [2024-11-12 13시 19분 17초] [info] [LaunchSuite]: Sending selected account (DriveBird) to ProcessBuilder.
C:\Users\acpro\Documents\GitHub\dosaonline\node_modules\winston\lib\winston\transports\console.js:90 [2024-11-12 13시 19분 17초] [info] [ProcessBuilder]: Using liteloader: false
C:\Users\acpro\Documents\GitHub\dosaonline\node_modules\winston\lib\winston\transports\console.js:90 [2024-11-12 13시 19분 17초] [info] [ProcessBuilder]: Using fabric loader: true
C:\Users\acpro\Documents\GitHub\dosaonline\node_modules\winston\lib\winston\transports\console.js:90 [2024-11-12 13시 19분 17초] [info] [ProcessBuilder]: Launch Arguments: [
  '-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump',
  '-Djava.library.path=C:\\Users\\acpro\\AppData\\Local\\Temp\\WCNatives\\7f02401f9f670c738e72a364e8c61bed',
  '-Djna.tmpdir=C:\\Users\\acpro\\AppData\\Local\\Temp\\WCNatives\\7f02401f9f670c738e72a364e8c61bed',
  '-Dorg.lwjgl.system.SharedLibraryExtractPath=C:\\Users\\acpro\\AppData\\Local\\Temp\\WCNatives\\7f02401f9f670c738e72a364e8c61bed',
  '-Dio.netty.native.workdir=C:\\Users\\acpro\\AppData\\Local\\Temp\\WCNatives\\7f02401f9f670c738e72a364e8c61bed',
  '-Dminecraft.launcher.brand=Helios-Launcher',
  '-Dminecraft.launcher.version=1.0.0',
  '-cp',
  'C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\versions\\1.21.3\\1.21.3.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\org\\ow2\\asm\\asm\\9.7.1\\asm-9.7.1.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\org\\ow2\\asm\\asm-analysis\\9.7.1\\asm-analysis-9.7.1.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\org\\ow2\\asm\\asm-commons\\9.7.1\\asm-commons-9.7.1.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\org\\ow2\\asm\\asm-tree\\9.7.1\\asm-tree-9.7.1.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\org\\ow2\\asm\\asm-util\\9.7.1\\asm-util-9.7.1.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\net\\fabricmc\\sponge-mixin\\0.15.4+mixin.0.8.7\\sponge-mixin-0.15.4+mixin.0.8.7.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\net\\fabricmc\\intermediary\\1.21.3\\intermediary-1.21.3.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\com\\fasterxml\\jackson\\core\\jackson-annotations\\2.13.4\\jackson-annotations-2.13.4.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\com\\fasterxml\\jackson\\core\\jackson-core\\2.13.4\\jackson-core-2.13.4.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\com\\fasterxml\\jackson\\core\\jackson-databind\\2.13.4.2\\jackson-databind-2.13.4.2.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\com\\github\\oshi\\oshi-core\\6.4.10\\oshi-core-6.4.10.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\com\\github\\stephenc\\jcip\\jcip-annotations\\1.0-1\\jcip-annotations-1.0-1.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\com\\google\\code\\gson\\gson\\2.10.1\\gson-2.10.1.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\com\\google\\guava\\failureaccess\\1.0.1\\failureaccess-1.0.1.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\com\\google\\guava\\guava\\32.1.2-jre\\guava-32.1.2-jre.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\com\\ibm\\icu\\icu4j\\73.2\\icu4j-73.2.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\com\\microsoft\\azure\\msal4j\\1.15.0\\msal4j-1.15.0.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\com\\mojang\\authlib\\6.0.55\\authlib-6.0.55.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\com\\mojang\\blocklist\\1.0.10\\blocklist-1.0.10.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\com\\mojang\\brigadier\\1.3.10\\brigadier-1.3.10.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\com\\mojang\\datafixerupper\\8.0.16\\datafixerupper-8.0.16.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\com\\mojang\\jtracy\\1.0.29\\jtracy-1.0.29.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\com\\mojang\\logging\\1.4.9\\logging-1.4.9.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\com\\mojang\\patchy\\2.2.10\\patchy-2.2.10.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\com\\mojang\\text2speech\\1.17.9\\text2speech-1.17.9.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\com\\nimbusds\\content-type\\2.3\\content-type-2.3.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\com\\nimbusds\\lang-tag\\1.7\\lang-tag-1.7.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\com\\nimbusds\\nimbus-jose-jwt\\9.37.3\\nimbus-jose-jwt-9.37.3.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\com\\nimbusds\\oauth2-oidc-sdk\\11.9.1\\oauth2-oidc-sdk-11.9.1.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\commons-codec\\commons-codec\\1.16.0\\commons-codec-1.16.0.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\commons-io\\commons-io\\2.15.1\\commons-io-2.15.1.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\commons-logging\\commons-logging\\1.2\\commons-logging-1.2.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\io\\netty\\netty-buffer\\4.1.97.Final\\netty-buffer-4.1.97.Final.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\io\\netty\\netty-codec\\4.1.97.Final\\netty-codec-4.1.97.Final.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\io\\netty\\netty-common\\4.1.97.Final\\netty-common-4.1.97.Final.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\io\\netty\\netty-handler\\4.1.97.Final\\netty-handler-4.1.97.Final.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\io\\netty\\netty-resolver\\4.1.97.Final\\netty-resolver-4.1.97.Final.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\io\\netty\\netty-transport-classes-epoll\\4.1.97.Final\\netty-transport-classes-epoll-4.1.97.Final.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\io\\netty\\netty-transport-native-unix-common\\4.1.97.Final\\netty-transport-native-unix-common-4.1.97.Final.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\io\\netty\\netty-transport\\4.1.97.Final\\netty-transport-4.1.97.Final.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\it\\unimi\\dsi\\fastutil\\8.5.12\\fastutil-8.5.12.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\net\\java\\dev\\jna\\jna-platform\\5.14.0\\jna-platform-5.14.0.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\net\\java\\dev\\jna\\jna\\5.14.0\\jna-5.14.0.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\net\\minidev\\accessors-smart\\2.5.0\\accessors-smart-2.5.0.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\net\\minidev\\json-smart\\2.5.0\\json-smart-2.5.0.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\net\\sf\\jopt-simple\\jopt-simple\\5.0.4\\jopt-simple-5.0.4.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\org\\apache\\commons\\commons-compress\\1.26.0\\commons-compress-1.26.0.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\org\\apache\\commons\\commons-lang3\\3.14.0\\commons-lang3-3.14.0.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\org\\apache\\httpcomponents\\httpclient\\4.5.13\\httpclient-4.5.13.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\org\\apache\\httpcomponents\\httpcore\\4.4.16\\httpcore-4.4.16.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\org\\apache\\logging\\log4j\\log4j-api\\2.22.1\\log4j-api-2.22.1.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\org\\apache\\logging\\log4j\\log4j-core\\2.22.1\\log4j-core-2.22.1.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\org\\apache\\logging\\log4j\\log4j-slf4j2-impl\\2.22.1\\log4j-slf4j2-impl-2.22.1.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\org\\jcraft\\jorbis\\0.0.17\\jorbis-0.0.17.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\org\\joml\\joml\\1.10.5\\joml-1.10.5.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\org\\lwjgl\\lwjgl-freetype\\3.3.3\\lwjgl-freetype-3.3.3.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\org\\lwjgl\\lwjgl-glfw\\3.3.3\\lwjgl-glfw-3.3.3.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\org\\lwjgl\\lwjgl-jemalloc\\3.3.3\\lwjgl-jemalloc-3.3.3.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\org\\lwjgl\\lwjgl-openal\\3.3.3\\lwjgl-openal-3.3.3.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\org\\lwjgl\\lwjgl-opengl\\3.3.3\\lwjgl-opengl-3.3.3.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\org\\lwjgl\\lwjgl-stb\\3.3.3\\lwjgl-stb-3.3.3.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\org\\lwjgl\\lwjgl-tinyfd\\3.3.3\\lwjgl-tinyfd-3.3.3.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\org\\lwjgl\\lwjgl\\3.3.3\\lwjgl-3.3.3.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\org\\lz4\\lz4-java\\1.8.0\\lz4-java-1.8.0.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\org\\ow2\\asm\\asm\\9.3\\asm-9.3.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\org\\slf4j\\slf4j-api\\2.0.9\\slf4j-api-2.0.9.jar;C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\libraries\\net\\fabricmc\\fabric-loader\\0.16.9\\fabric-loader-0.16.9.jar',
  '-DFabricMcEmu= net.minecraft.client.main.Main ',
  '-Xmx4G',
  '-Xms4G',
  '-XX:+UnlockExperimentalVMOptions',
  '-XX:+UseG1GC',
  '-XX:G1NewSizePercent=20',
  '-XX:G1ReservePercent=20',
  '-XX:MaxGCPauseMillis=50',
  '-XX:G1HeapRegionSize=32M',
  'net.fabricmc.loader.impl.launch.knot.KnotClient',
  '--username',
  'DriveBird',
  '--version',
  'Dosaonline-1.21.3',
  '--gameDir',
  'C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\instances\\Dosaonline-1.21.3',
  '--assetsDir',
  'C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\common\\assets',
  '--assetIndex',
  '18',
  '--uuid',
  'da90cd1840564e7a9f378576bdea2257',
  '--accessToken',
  'eyJraWQiOiJhYzg0YSIsImFsZyI6IkhTMjU2In0.eyJ4dWlkIjoiMjUzNTQxNzg2OTA4NDIyNyIsImFnZyI6IkFkdWx0Iiwic3ViIjoiM2I1YTI4OWYtYTM4OC00MGNjLWIzOWEtYTYyNDM4MDhiNDNlIiwiYXV0aCI6IlhCT1giLCJucyI6ImRlZmF1bHQiLCJyb2xlcyI6W10sImlzcyI6ImF1dGhlbnRpY2F0aW9uIiwiZmxhZ3MiOlsidHdvZmFjdG9yYXV0aCIsIm1zYW1pZ3JhdGlvbl9zdGFnZTQiLCJvcmRlcnNfMjAyMiIsIm11bHRpcGxheWVyIl0sInByb2ZpbGVzIjp7Im1jIjoiZGE5MGNkMTgtNDA1Ni00ZTdhLTlmMzctODU3NmJkZWEyMjU3In0sInBsYXRmb3JtIjoiVU5LTk9XTiIsInl1aWQiOiJjMjMxNGZmNDY3OWQ0OTI1YTMwOTE2Mzc1ZTZmOTA1OSIsIm5iZiI6MTczMTM4NTAxOCwiZXhwIjoxNzMxNDcxNDE4LCJpYXQiOjE3MzEzODUwMTh9.8evBCznlHSem0n19pqsRRegRf-eGOrAgxQyX20rigLs',
  '--clientId',
  '${clientid}',
  '--xuid',
  '${auth_xuid}',
  '--userType',
  'msa',
  '--versionType',
  'release',
  '--width',
  1280,
  '--height',
  720,
  '--quickPlayMultiplayer',
  'dosaonline.kr:24100',
  '--fabric.addMods',
  '@C:\\Users\\acpro\\AppData\\Roaming\\.helioslauncher\\instances\\Dosaonline-1.21.3\\forgeMods.list'
]
C:\Users\acpro\Documents\GitHub\dosaonline\app\assets\js\processbuilder.js:93 [Minecraft] Exception in thread "main"
C:\Users\acpro\Documents\GitHub\dosaonline\app\assets\js\processbuilder.js:93 [Minecraft] java.lang.ExceptionInInitializerError
C:\Users\acpro\Documents\GitHub\dosaonline\app\assets\js\processbuilder.js:93 [Minecraft] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
C:\Users\acpro\Documents\GitHub\dosaonline\app\assets\js\processbuilder.js:93 [Minecraft] Caused by: java.lang.IllegalStateException: duplicate ASM classes found on classpath: jar:file:/C:/Users/acpro/AppData/Roaming/.helioslauncher/common/libraries/org/ow2/asm/asm/9.7.1/asm-9.7.1.jar!/org/objectweb/asm/ClassReader.class, jar:file:/C:/Users/acpro/AppData/Roaming/.helioslauncher/common/libraries/org/ow2/asm/asm/9.3/asm-9.3.jar!/org/objectweb/asm/ClassReader.class
C:\Users\acpro\Documents\GitHub\dosaonline\app\assets\js\processbuilder.js:93 [Minecraft] 	at net.fabricmc.loader.impl.util.LoaderUtil.verifyClasspath(LoaderUtil.java:83)
C:\Users\acpro\Documents\GitHub\dosaonline\app\assets\js\processbuilder.js:93 [Minecraft] 	at net.fabricmc.loader.impl.launch.knot.Knot.<clinit>(Knot.java:345)
C:\Users\acpro\Documents\GitHub\dosaonline\app\assets\js\processbuilder.js:93 [Minecraft] 	... 1 more
C:\Users\acpro\Documents\GitHub\dosaonline\node_modules\winston\lib\winston\transports\console.js:90 [2024-11-12 13시 19분 18초] [info] [ProcessBuilder]: Exited with code 1
C:\Users\acpro\Documents\GitHub\dosaonline\node_modules\winston\lib\winston\transports\console.js:90 [2024-11-12 13시 19분 18초] [info] [ProcessBuilder]: Temp dir deleted successfully.```

@GeekCornerGH

**Comment by GeekCornerGH** [comment]
Try to clear the .helioslauncher folder. Also be careful next times as you leaked your accesstoken

**Comment by interacp** [comment]
@GeekCornerGH 
I've deleted the access token. Thank you for letting me know.
I completely deleted that folder and ran it again, but the same error still occurs. I don't see version 9.3 anywhere in my code, but it keeps downloading and causing conflicts. Is this issue only happening to me? I really need launcher version 1.21.3, but I can't figure out the problem.

**Comment by interacp** [comment]
@GeekCornerGH 
I found the problematic path:  
`C:\Users\user\AppData\Roaming\.FreeServer\common\versions`.  
Along with `1.21.3-fabric-0.16.9`, a `1.21.3` folder is created here, and in this folder’s `1.21.3.json`, version 9.3 is listed as a dependency. Even if I delete the `1.21.3` folder, it gets reinstalled during execution, and version 9.3 is installed according to `1.21.3.json`, causing conflicts. Is there any way to fix this?

**Comment by interacp** [comment]
Currently, with Fabric 1.21.3, the issue described above is occurring on certain custom launchers rather than the official Minecraft launcher, and I am seeing the same issue with both Nebula and Helios. Is there any way to resolve this? Running Fabric 1.21.3 through the official launcher or using Cusforge with the official launcher works without issues, but other custom launchers are currently unable to run Fabric due to the same conflict seen with Helios. It seems like this might need to be addressed within the launcher itself. Would that be possible?

**Comment by GeekCornerGH** [comment]
@dscalzi do you have some time to troubleshoot this?

**Comment by interacp** [comment]
@dscalzi I know you must be very busy, but I would greatly appreciate any help you can provide to resolve this issue

**Comment by dscalzi** [comment]
I'll try to launch it

**Comment by dscalzi** [comment]
Caused by: java.lang.IllegalStateException: duplicate ASM classes found on classpath: jar:file:/E:/HeliosLauncherTest/common/libraries/org/ow2/asm/asm/9.7.1/asm-9.7.1.jar!/org/objectweb/asm/ClassReader.class, jar:file:/E:/HeliosLauncherTest/common/libraries/org/ow2/asm/asm/9.3/asm-9.3.jar!/org/objectweb/asm/ClassReader.class

Looks like an issue with the classpath

**Comment by dscalzi** [comment]
Fabriv wants 9.7.1, vanilla wants 9.3. The launcher is supposed to override that though, let me see why it isnt.

**Comment by dscalzi** [comment]
@interacp Pull that commit and lmk if it fixes your issue

**Comment by interacp** [comment]
@dscalzi 
The ASM errors are no longer occurring! 
A few mods are still causing conflicts, but they aren’t essential, so it’s just a minor issue.
Now I can use the launcher! Thank you so much!
