### ISSUE TITLE
Unable to canonicalize path absolute

### ISSUE THREAD

**Issue by Sunloos** [dscalzi/HeliosLauncher#45]
This Error :
Unable to canonicalize path absolute:C:\Users\Sunloos\AppData\Roaming\.summermc\instances\summermc\forgeModList.json relative to C:\Users\Sunloos\AppData\Roaming\.summermc\instances\summermc
java.io.IOException: La syntaxe du nom de fichier, de r�pertoire ou de volume est incorrecte
	at java.io.WinNTFileSystem.canonicalize0(Native Method) ~[?:1.8.0_231]
	at java.io.WinNTFileSystem.canonicalize(Unknown Source) ~[?:1.8.0_231]
	at java.io.File.getCanonicalPath(Unknown Source) ~[?:1.8.0_231]
	at java.io.File.getCanonicalFile(Unknown Source) ~[?:1.8.0_231]
	at cpw.mods.fml.relauncher.ModListHelper.parseListFile(ModListHelper.java:51) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.ModListHelper.parseModList(ModListHelper.java:35) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:227) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

**I can't find any solution**

**Comment by dscalzi** [comment]
Can you send me your distribution.json

**Comment by Verttigo28** [comment]
Hi, What was the solution for that?
Thanks
