### ISSUE TITLE
[1.8] Launch crash

### ISSUE THREAD

**Issue by AlphineGhost** [dscalzi/HeliosLauncher#58]
`[06:35:46] [Client thread/INFO]: [net.minecraft.init.Bootstrap:func_179870_a:529]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  BlurPlugin (Blur-MC1.8.9-1.0.4-2.jar)
  ShoulderPlugin (ShoulderSurfing-1.8.8_1.8.9-1.1.jar)
  FMLLoadingPlugin (MemoryFix-0.3.jar)
  AppleCore (AppleCore-mc1.8.9-3.1.1.jar)
  FMLPlugin (InventoryTweaks-1.60-40.jar)
  CorePlugin (SmoothFont-1.8.9-1.15.2.jar)
  FMLLoadingPlugin (MouseDelayFix-1.0.jar)
  LoadingPlugin (ResourceLoader-MC1.8.8-1.4.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 4/20/20 6:35 AM
Description: Initializing game

java.lang.NoClassDefFoundError: gnu/trove/map/hash/TByteObjectHashMap
	at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.<init>(FMLIndexedMessageToMessageCodec.java:23)
	at net.minecraftforge.fml.common.network.internal.FMLRuntimeCodec.<init>(FMLRuntimeCodec.java:15)
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.registerChannel(FMLNetworkHandler.java:172)
	at net.minecraftforge.fml.common.FMLContainer.modConstruction(FMLContainer.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:512)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:417)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: gnu.trove.map.hash.TByteObjectHashMap
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 36 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 38 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.<init>(FMLIndexedMessageToMessageCodec.java:23)
	at net.minecraftforge.fml.common.network.internal.FMLRuntimeCodec.<init>(FMLRuntimeCodec.java:15)
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.registerChannel(FMLNetworkHandler.java:172)
	at net.minecraftforge.fml.common.FMLContainer.modConstruction(FMLContainer.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:512)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:417)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	CPU: 4x Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
	Java Version: 1.8.0_252, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), AdoptOpenJDK
	Memory: 5183032264 bytes (4942 MB) / 5355339776 bytes (5107 MB) up to 5355339776 bytes (5107 MB)
	JVM Flags: 6 total; -Xmx5G -Xms5G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 Optifine OptiFine_1.8.9_HD_U_I7 30 mods loaded, 30 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	U	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318.jar) 
	U	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318.jar) 
	U	mousedelayfix{1.0} [MouseDelayFix] (minecraft.jar) 
	U	smoothfontcore{1.8.9-1.15.1} [Smooth Font Core] (minecraft.jar) 
	U	smoothfont{1.8.9-1.15.2} [Smooth Font] (SmoothFont-1.8.9-1.15.2.jar) 
	U	fullbright{1.2} [Fullbright] (1.8.9-Fullbright-v1.2.1.jar) 
	U	sidebarmod{2.0} [Sidebar Mod Revamp] ([1.8.9] Sidebar Mod Revamp.jar) 
	U	JEI{2.28.18.187} [Just Enough Items] (jei_1.8.9-2.28.18.187.jar) 
	U	AppleCore{3.1.1} [AppleCore] (AppleCore-mc1.8.9-3.1.1.jar) 
	U	hud{1.3.7} [Better HUD] (Better HUD by NukeDuck [1.8.9][1.3.7].jar) 
	U	blur{MC1.8.9-1.0.4-2} [Blur] (Blur-MC1.8.9-1.0.4-2.jar) 
	U	MineTweaker3{3.1.0} [MineTweaker 3] (CraftTweaker-1.8.9-3.1.0-legacy.jar) 
	U	CustomMainMenu{2.0} [Custom Main Menu] (CustomMainMenu-MC1.8.9-2.0.jar) 
	U	fbp{2.4.1} [Fancy Block Particles] (FancyBlockParticles-1.8.9-2.4.1.jar) 
	U	IngameAccountSwitcher{7.0.1} [In-Game Account Switcher] (InGameAccountSwitcher-Forge-1.8.9-7.0.1.jar) 
	U	inventorytweaks{1.60-40-e06e29a} [Inventory Tweaks] (InventoryTweaks-1.60-40.jar) 
	U	journeymap{1.8.9-5.2.4} [JourneyMap] (journeymap-1.8.9-5.2.4-unlimited.jar) 
	U	memoryfix{0.3} [MemoryFix] (MemoryFix-0.3.jar) 
	U	mercurius{1.0.6} [Mercurius] (Mercurius-1.8.9-1.0.6.jar) 
	U	MouseTweaks{2.6.2} [Mouse Tweaks] (MouseTweaks-2.6.2-mc1.8.9.jar) 
	U	musicplayer{2.0.3.55} [Music Player] (music_player-1.8.9-2.0.3.55.jar) 
	U	reauth{3.5.0} [ReAuth] (ReAuth-3.5.0.jar) 
	U	ResourceLoader{1.4} [Resource Loader] (ResourceLoader-MC1.8.8-1.4.jar) 
	U	shouldersurfing{1.1} [Shoulder Surfing] (ShoulderSurfing-1.8.8_1.8.9-1.1.jar) 
	U	torohealthmod{1.8.9-7} [ToroHealth Damage Indicators] (torohealth-1.8.9-7.jar) 
	U	uteamcore{1.3.0.63} [UTeam Core] (U-Team-Core-1.8.9.jar) 
	U	Waila{1.6.0} [Waila] (Waila-1.6.0-B3_1.8.8.jar) 
	U	wawla{1.1.4.168} [What Are We Looking At] (Wawla-1.8.9-1.1.4.170.jar) 
	U	worldedit{6.1.1} [WorldEdit] (worldedit-forge-mc1.8.9-6.1.1.jar) 
	Loaded coremods (and transformers): 
BlurPlugin (Blur-MC1.8.9-1.0.4-2.jar)
  com.tterrag.blur.BlurTransformer
ShoulderPlugin (ShoulderSurfing-1.8.8_1.8.9-1.1.jar)
  com.teamderpy.shouldersurfing.asm.ShoulderTransformations
FMLLoadingPlugin (MemoryFix-0.3.jar)
  io.prplz.memoryfix.ClassTransformer
AppleCore (AppleCore-mc1.8.9-3.1.1.jar)
  squeek.applecore.asm.TransformerModuleHandler
FMLPlugin (InventoryTweaks-1.60-40.jar)
  invtweaks.forge.asm.ContainerTransformer
CorePlugin (SmoothFont-1.8.9-1.15.2.jar)
  bre.smoothfont.asm.Transformer
FMLLoadingPlugin (MouseDelayFix-1.0.jar)
  io.prplz.mousedelayfix.ClassTransformer
LoadingPlugin (ResourceLoader-MC1.8.8-1.4.jar)
  lumien.resourceloader.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 442.05' Renderer: 'GeForce GTX 1060 3GB/PCIe/SSE2'
	Launched Version: 1.8.9
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1060 3GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 442.05, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
`
Trying to add my own mod pack for the launcher. By the way, I didn't use any of the preset forge.

**Comment by AlphineGhost** [comment]
Made a new and different dist file

**Comment by dscalzi** [comment]
You're missing a required library. Generate the distribution with [Nebula](https://github.com/dscalzi/Nebula).

```java.lang.NoClassDefFoundError: gnu/trove/map/hash/TByteObjectHashMap
```
