### ISSUE TITLE
Mods not loading on 1.9.4

### ISSUE THREAD

**Issue by NhProGamer** [dscalzi/HeliosLauncher#79]
**Error:**
[Minecraft] [19:13:59] [main/INFO]: Unable to canonicalize path absolute:C:\Users\nhpro\AppData\Roaming\.universe-pvp\instances\universepvp-1.9.4\forgeModList.json relative to C:\Users\nhpro\AppData\Roaming\.universe-pvp\instances\universepvp-1.9.4
java.io.IOException: La syntaxe du nom de fichier, de r�pertoire ou de volume est incorrecte
	at java.io.WinNTFileSystem.canonicalize0(Native Method) ~[?:1.8.0_251]
	at java.io.WinNTFileSystem.canonicalize(Unknown Source) ~[?:1.8.0_251]
	at java.io.File.getCanonicalPath(Unknown Source) ~[?:1.8.0_251]
	at java.io.File.getCanonicalFile(Unknown Source) ~[?:1.8.0_251]
	at net.minecraftforge.fml.relauncher.ModListHelper.parseListFile(ModListHelper.java:51) [forge-1.9.4-12.17.0.2051-universal.jar:?]
	at net.minecraftforge.fml.relauncher.ModListHelper.parseModList(ModListHelper.java:35) [forge-1.9.4-12.17.0.2051-universal.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:252) [forge-1.9.4-12.17.0.2051-universal.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:246) [forge-1.9.4-12.17.0.2051-universal.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:95) [forge-1.9.4-12.17.0.2051-universal.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:72) [forge-1.9.4-12.17.0.2051-universal.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [forge-1.9.4-12.17.0.2051-universal.jar:?]
	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:119) [forge-1.9.4-12.17.0.2051-universal.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
**Is there a solution ?**

here is my distribution file:
https://files.nhsoul.fr/launchers/UniversePVP/distribution.json

**Comment by NhProGamer** [comment]
my distribution file was generate by Nebula

**Comment by LaFunAttitude-Dev** [comment]
hello I have the same problem

**Comment by NhProGamer** [comment]
Je me disait bien que je n'étais pas la seule personnne a avoir le meme problème (Ah et ça fait plaisir de croiser un français)
I tell myself that I was not the only person with the same problem(google trad but i' mfrench)

**Comment by dscalzi** [comment]
Also affects `1.8.9`

**Comment by LaFunAttitude-Dev** [comment]
and 1.7.10, please correct this problem

**Comment by dscalzi** [comment]
> and 1.7.10, please correct this problem

1.7.10 has been verified working for a while now.
